# Generated by Django 4.1.2 on 2023-01-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("add_logo", models.CharField(max_length=100, null=True)),
                ("bank_name", models.CharField(max_length=100)),
                ("bank_account_number", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("bank_account_name", models.CharField(max_length=100)),
                ("branch_name", models.CharField(max_length=100)),
                ("is_term", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Declined", "Declined"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("read", "Read"), ("unread", "Unread")], max_length=20
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RequestMobileBankModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("phone_number", models.CharField(max_length=100)),
                ("bank_name", models.CharField(max_length=100)),
                ("add_logo", models.CharField(max_length=100, null=True)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                (
                    "choice",
                    models.CharField(
                        choices=[("Personal", "Personal"), ("Agent", "Agent")],
                        max_length=10,
                    ),
                ),
                ("is_term", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Declined", "Declined"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequestMobileRechargeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=100, null=True)),
                ("amount", models.IntegerField()),
                ("add_logo", models.CharField(max_length=100, null=True)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("phone_number", models.CharField(max_length=100)),
                (
                    "choice",
                    models.CharField(
                        choices=[("Prepaid", "Prepaid"), ("Postpaid", "Postpaid")],
                        max_length=10,
                    ),
                ),
                ("is_term", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Declined", "Declined"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
