# Generated by Django 4.1.2 on 2022-11-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_request", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankingmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Declined", "Declined"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="requestmobilebankmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Declined", "Declined"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="requestmobilerechargemodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Declined", "Declined"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
