# Generated by Django 4.1.2 on 2023-01-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_request", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bankingmodel",
            options={"verbose_name_plural": "Banking"},
        ),
        migrations.AlterModelOptions(
            name="requestmobilebankmodel",
            options={
                "verbose_name": "Mobile Banking",
                "verbose_name_plural": "Mobile Banking",
            },
        ),
        migrations.AlterModelOptions(
            name="requestmobilerechargemodel",
            options={"verbose_name_plural": "Mobile Recharge"},
        ),
        migrations.AddField(
            model_name="bankingmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="requestmobilebankmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="requestmobilerechargemodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name="NotificationModel",
        ),
    ]
