# Generated by Django 4.1.2 on 2022-11-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_request", "0003_alter_bankingmodel_is_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestmobilebankmodel",
            name="is_term",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="requestmobilerechargemodel",
            name="is_term",
            field=models.BooleanField(),
        ),
    ]
