# Generated by Django 4.1.2 on 2022-11-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_request", "0004_alter_requestmobilebankmodel_is_term_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestmobilebankmodel",
            name="bank_name",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
