# Generated by Django 4.1.2 on 2022-12-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_request", "0006_bankingmodel_add_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankingmodel",
            name="ip_address",
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name="requestmobilebankmodel",
            name="ip_address",
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name="requestmobilerechargemodel",
            name="bank_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="requestmobilerechargemodel",
            name="ip_address",
            field=models.GenericIPAddressField(null=True),
        ),
    ]
