# Generated by Django 4.1.2 on 2023-01-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankingMethod",
            fields=[
                (
                    "auto_increment_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=20)),
                ("logo", models.ImageField(upload_to="logo")),
                (
                    "types",
                    models.CharField(
                        choices=[
                            ("Mobile Banking", "Mobile Banking"),
                            ("Bank", "Bank"),
                            ("Mobile Recharge", "Mobile Recharge"),
                            ("Gift Card", "Gift Card"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
