# Generated by Django 4.1.2 on 2022-11-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankingmethod",
            name="types",
            field=models.CharField(
                choices=[
                    ("Mobile Banking", "Mobile Banking"),
                    ("Bank", "Bank"),
                    ("Mobile Recharge", "Mobile Recharge"),
                    ("Gift Card", "Gift Card"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="BankingType",
        ),
    ]
