# Generated by Django 4.1.2 on 2022-11-09 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0002_alter_bankingmethod_types_delete_bankingtype"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BankingMethod",
        ),
    ]
