# Generated by Django 4.1.2 on 2022-11-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("banking", "0003_delete_bankingmethod"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankingMethod",
            fields=[
                (
                    "auto_increment_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=20)),
                ("logo", models.ImageField(upload_to="logos")),
            ],
        ),
        migrations.CreateModel(
            name="BankingType",
            fields=[
                (
                    "auto_increment_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
    ]
