# Generated by Django 4.1.2 on 2022-11-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankingmethod",
            name="logo",
            field=models.ImageField(upload_to="media"),
        ),
    ]
