# Generated by Django 4.1.2 on 2022-11-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0006_alter_bankingmethod_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankingmethod",
            name="types",
            field=models.CharField(
                choices=[
                    ("Mobile Banking", "Mobile Banking"),
                    ("Bank", "Bank"),
                    ("Mobile Recharge", "Mobile Recharge"),
                    ("Gift Card", "Gift Card"),
                ],
                default=None,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bankingmethod",
            name="logo",
            field=models.FileField(upload_to=""),
        ),
    ]
