# Generated by Django 4.1.2 on 2022-11-20 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0008_alter_bankingmethod_logo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BankingType",
        ),
    ]
