# Generated by Django 4.1.2 on 2022-12-10 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0009_delete_bankingtype"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BankingMethod",
        ),
    ]
