# Generated by Django 4.1.2 on 2022-11-27 17:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0003_alter_newuser_mobile_recharge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="mobile_recharge",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Airtel", "Airtel"),
                    ("Banglalink", "Banglalink"),
                    ("Grameen Phone", "Grameen Phone"),
                    ("Robi", "Robi"),
                    ("Teletalk", "Teletalk"),
                ],
                default="Airtel",
                max_length=100,
            ),
        ),
    ]
