# Generated by Django 4.1.2 on 2022-11-29 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0004_alter_newuser_mobile_recharge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newuser",
            name="bank",
        ),
        migrations.RemoveField(
            model_name="newuser",
            name="mobile_banking",
        ),
        migrations.RemoveField(
            model_name="newuser",
            name="mobile_recharge",
        ),
    ]
