# Generated by Django 4.1.2 on 2022-12-10 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0006_newuser_bank_newuser_mobile_banking_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newuser",
            name="bank",
        ),
        migrations.RemoveField(
            model_name="newuser",
            name="mobile_banking",
        ),
        migrations.RemoveField(
            model_name="newuser",
            name="mobile_recharge",
        ),
    ]
