# Generated by Django 4.1.2 on 2022-12-10 04:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0007_remove_newuser_bank_remove_newuser_mobile_banking_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="bank",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Asia", "Asia"),
                    ("Brack", "Brack"),
                    ("City", "City"),
                    ("DBBL", "DBBL"),
                    ("EBL", "EBL"),
                    ("Exim", "Exim"),
                    ("Islami", "Islami"),
                    ("MTB", "MTB"),
                    ("One", "One"),
                    ("Prime", "Prime"),
                    ("UCB", "UCB"),
                ],
                default="Asia",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="newuser",
            name="mobile_banking",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Bkash", "Bkash"),
                    ("Surecash", "Surecash"),
                    ("Mcash", "Mcash"),
                    ("Roket", "Roket"),
                    ("Upay", "Upay"),
                    ("Nagad", "Nagad"),
                ],
                default="Bkash",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="newuser",
            name="mobile_recharge",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Airtel", "Airtel"),
                    ("Banglalink", "Banglalink"),
                    ("Grameenphone", "Grameenphone"),
                    ("Robi", "Robi"),
                    ("Teletalk", "Teletalk"),
                ],
                default="Airtel",
                max_length=100,
            ),
        ),
    ]
