# Generated by Django 4.1.2 on 2022-12-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0008_newuser_bank_newuser_mobile_banking_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="isReseller",
            field=models.BooleanField(default=False),
        ),
    ]
