# Generated by Django 4.1.2 on 2022-12-11 05:08

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0009_newuser_isreseller"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="gift_card",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("TAP", "TAP"),
                    ("Google Pay", "Google Pay"),
                    ("Amazone", "Amazone"),
                ],
                default=None,
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
